//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PhoneApp1.wsServico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.com.br/", ConfigurationName="wsServico.TesteJavaWs")]
    public interface TesteJavaWs {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginreturnServico(PhoneApp1.wsServico.returnServico request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.wsServico.returnServicoResponse EndreturnServico(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.com.br/")]
    public partial class cadastroTo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long cadastroIdField;
        
        private bool cadastroIdFieldSpecified;
        
        private int quantidadeField;
        
        private bool quantidadeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long cadastroId {
            get {
                return this.cadastroIdField;
            }
            set {
                this.cadastroIdField = value;
                this.RaisePropertyChanged("cadastroId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cadastroIdSpecified {
            get {
                return this.cadastroIdFieldSpecified;
            }
            set {
                this.cadastroIdFieldSpecified = value;
                this.RaisePropertyChanged("cadastroIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantidadeSpecified {
            get {
                return this.quantidadeFieldSpecified;
            }
            set {
                this.quantidadeFieldSpecified = value;
                this.RaisePropertyChanged("quantidadeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnServico", WrapperNamespace="http://webservices.com.br/", IsWrapped=true)]
    public partial class returnServico {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parametro1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parametro2;
        
        public returnServico() {
        }
        
        public returnServico(string parametro1, string parametro2) {
            this.parametro1 = parametro1;
            this.parametro2 = parametro2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnServicoResponse", WrapperNamespace="http://webservices.com.br/", IsWrapped=true)]
    public partial class returnServicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PhoneApp1.wsServico.cadastroTo @return;
        
        public returnServicoResponse() {
        }
        
        public returnServicoResponse(PhoneApp1.wsServico.cadastroTo @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TesteJavaWsChannel : PhoneApp1.wsServico.TesteJavaWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class returnServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public returnServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PhoneApp1.wsServico.cadastroTo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PhoneApp1.wsServico.cadastroTo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TesteJavaWsClient : System.ServiceModel.ClientBase<PhoneApp1.wsServico.TesteJavaWs>, PhoneApp1.wsServico.TesteJavaWs {
        
        private BeginOperationDelegate onBeginreturnServicoDelegate;
        
        private EndOperationDelegate onEndreturnServicoDelegate;
        
        private System.Threading.SendOrPostCallback onreturnServicoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TesteJavaWsClient() {
        }
        
        public TesteJavaWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TesteJavaWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesteJavaWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesteJavaWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<returnServicoCompletedEventArgs> returnServicoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.wsServico.TesteJavaWs.BeginreturnServico(PhoneApp1.wsServico.returnServico request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginreturnServico(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginreturnServico(string parametro1, string parametro2, System.AsyncCallback callback, object asyncState) {
            PhoneApp1.wsServico.returnServico inValue = new PhoneApp1.wsServico.returnServico();
            inValue.parametro1 = parametro1;
            inValue.parametro2 = parametro2;
            return ((PhoneApp1.wsServico.TesteJavaWs)(this)).BeginreturnServico(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.wsServico.returnServicoResponse PhoneApp1.wsServico.TesteJavaWs.EndreturnServico(System.IAsyncResult result) {
            return base.Channel.EndreturnServico(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private PhoneApp1.wsServico.cadastroTo EndreturnServico(System.IAsyncResult result) {
            PhoneApp1.wsServico.returnServicoResponse retVal = ((PhoneApp1.wsServico.TesteJavaWs)(this)).EndreturnServico(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginreturnServico(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string parametro1 = ((string)(inValues[0]));
            string parametro2 = ((string)(inValues[1]));
            return this.BeginreturnServico(parametro1, parametro2, callback, asyncState);
        }
        
        private object[] OnEndreturnServico(System.IAsyncResult result) {
            PhoneApp1.wsServico.cadastroTo retVal = this.EndreturnServico(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreturnServicoCompleted(object state) {
            if ((this.returnServicoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.returnServicoCompleted(this, new returnServicoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void returnServicoAsync(string parametro1, string parametro2) {
            this.returnServicoAsync(parametro1, parametro2, null);
        }
        
        public void returnServicoAsync(string parametro1, string parametro2, object userState) {
            if ((this.onBeginreturnServicoDelegate == null)) {
                this.onBeginreturnServicoDelegate = new BeginOperationDelegate(this.OnBeginreturnServico);
            }
            if ((this.onEndreturnServicoDelegate == null)) {
                this.onEndreturnServicoDelegate = new EndOperationDelegate(this.OnEndreturnServico);
            }
            if ((this.onreturnServicoCompletedDelegate == null)) {
                this.onreturnServicoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreturnServicoCompleted);
            }
            base.InvokeAsync(this.onBeginreturnServicoDelegate, new object[] {
                        parametro1,
                        parametro2}, this.onEndreturnServicoDelegate, this.onreturnServicoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PhoneApp1.wsServico.TesteJavaWs CreateChannel() {
            return new TesteJavaWsClientChannel(this);
        }
        
        private class TesteJavaWsClientChannel : ChannelBase<PhoneApp1.wsServico.TesteJavaWs>, PhoneApp1.wsServico.TesteJavaWs {
            
            public TesteJavaWsClientChannel(System.ServiceModel.ClientBase<PhoneApp1.wsServico.TesteJavaWs> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginreturnServico(PhoneApp1.wsServico.returnServico request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("returnServico", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.wsServico.returnServicoResponse EndreturnServico(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.wsServico.returnServicoResponse _result = ((PhoneApp1.wsServico.returnServicoResponse)(base.EndInvoke("returnServico", _args, result)));
                return _result;
            }
        }
    }
}
